// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9-lzhSzKgDlE77_Rni1nu-scpmINZA0U',
    appId: '1:982938198507:web:4ae199b0b7dfc6cca2b9ae',
    messagingSenderId: '982938198507',
    projectId: 'wealthifyme-b2b92',
    authDomain: 'wealthifyme-b2b92.firebaseapp.com',
    storageBucket: 'wealthifyme-b2b92.appspot.com',
    measurementId: 'G-5VESRG064S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABY8quqrbOdDFxJ63EpoeB6kO1miOzlCY',
    appId: '1:982938198507:android:cb18e04d45a40bb6a2b9ae',
    messagingSenderId: '982938198507',
    projectId: 'wealthifyme-b2b92',
    storageBucket: 'wealthifyme-b2b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzgNg1YU22r1nVFFscjdKeRqC7WmC9umk',
    appId: '1:982938198507:ios:e16c30e6aa275e19a2b9ae',
    messagingSenderId: '982938198507',
    projectId: 'wealthifyme-b2b92',
    storageBucket: 'wealthifyme-b2b92.appspot.com',
    iosBundleId: 'com.example.wealthifyMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzgNg1YU22r1nVFFscjdKeRqC7WmC9umk',
    appId: '1:982938198507:ios:e16c30e6aa275e19a2b9ae',
    messagingSenderId: '982938198507',
    projectId: 'wealthifyme-b2b92',
    storageBucket: 'wealthifyme-b2b92.appspot.com',
    iosBundleId: 'com.example.wealthifyMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9-lzhSzKgDlE77_Rni1nu-scpmINZA0U',
    appId: '1:982938198507:web:c9845e3c4238c34ba2b9ae',
    messagingSenderId: '982938198507',
    projectId: 'wealthifyme-b2b92',
    authDomain: 'wealthifyme-b2b92.firebaseapp.com',
    storageBucket: 'wealthifyme-b2b92.appspot.com',
    measurementId: 'G-F2QDKSBBS4',
  );
}
